remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

theme: jekyll-theme-architect
title: Fran√ßois HU
description: About me, my research, my teaching and my experimentations
google_analytics: UA-163147530-1
logo: images/logo.png
logo1: images/logo1.png
logo2: images/logo2.png
photo: images/logo.png
linkedin: https://www.linkedin.com/in/fran%C3%A7ois-hu-9b6295136/?originalSubdomain=fr
